# Generated by Django 5.2.1 on 2025-05-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250512_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('ADMIN', 'Admin'), ('EMPLOYEE', 'Employee'), ('FINANCE', 'Finance'), ('SERVICES', 'Services'), ('SALES', 'Sales')], default='CUSTOMER', max_length=10),
        ),
    ]
